#pragma once

#include <QMetaType>
#include <QString>
#include <QtGlobal>

namespace okuflow {

// Live-transcription contracts shared by the realtime client, the session
// controller, the notes writer, and the UI. No UI dependencies belong here.

// Stable identity of one recording session. Generated by RecordingManager
// only after start preflight passes, and carried by every queued recorder
// callback so a delayed callback can never be associated with a newer
// session's transcript or notes (plan 36).
struct RecordingSessionInfo {
    QString id;              // QUuid without braces
    QString timestampToken;  // filename timestamp (yyyyMMdd_HHmmss_zzz)
};

// Recording and transcription stay independent: every state here describes
// the transcript only, and no state may gate recorder start, stop, or
// finalization.
enum class TranscriptionState {
    Off,          // feature disabled in settings
    Unavailable,  // capability missing for this app session
    Ready,        // enabled and idle
    Starting,     // account gate, thread, WebRTC negotiation in flight
    Listening,    // negotiated; partials may arrive
    Finalizing,   // input finished; bounded wait, then preserve streamed tail
    Completed,    // session ended; finals published
    Failed,       // session ended with an error; prior finals remain valid
};

struct TranscriptSegment {
    QString recordingSessionId;            // RecordingSessionInfo::id
    quint64 sequence{};                    // monotonic per recording session
    QString languageCode;                  // BCP-47-ish app language ("en")
    QString text;                          // finalized user speech, plain text
    bool truncated{false};                 // text hit kMaximumSegmentCharacters
    qint64 observedCaptureClock100ns{-1};  // QPC clock of newest sent audio
    qint64 approximateOffset100ns{-1};     // offset from recording start; approximate
};

namespace transcript_limits {

// One finalized phrase or locally preserved closing turn. Anything larger is
// truncated visibly rather than dropped.
inline constexpr qsizetype kMaximumSegmentCharacters = 8192;
// Rolling presentation tail; the controller separately retains at most one
// final-sized current turn for close-time preservation.
inline constexpr qsizetype kMaximumPartialCharacters = 2048;
// SDP offers/answers observed at ~2.5 KB; the cap only guards runaway input.
inline constexpr qsizetype kMaximumSdpCharacters = 64 * 1024;
// Transcript audio queue bounds (native carrier): never more than five
// seconds or its PCM byte equivalent is retained while WebRTC negotiates.
// This is a latency/backpressure bound, not an API upload chunk size: WebRTC
// is fed 20 ms frames continuously once the carrier is ready.
inline constexpr qint64 kMaximumQueuedAudio100ns = 5LL * 10000000LL;
inline constexpr qsizetype kMaximumQueuedAudioBytes =
    5 * 48000 * 2;  // five seconds of 48 kHz mono PCM16
// Carrier chunking: 20 ms at 48 kHz mono.
inline constexpr int kCarrierChunkSamples = 960;
inline constexpr int kCarrierChunkBytes = kCarrierChunkSamples * 2;
// At most a 100 ms batch is handed to the carrier at once.
inline constexpr int kMaximumBridgeBatchChunks = 5;

} // namespace transcript_limits

} // namespace okuflow

Q_DECLARE_METATYPE(okuflow::RecordingSessionInfo)
Q_DECLARE_METATYPE(okuflow::TranscriptSegment)
Q_DECLARE_METATYPE(okuflow::TranscriptionState)
